# https://golangci-lint.run/usage/configuration/#config-file
# ~/go/bin/golangci-lint run ./pkg/...
# gofmt -s -w ./pkg
linters:
  disable-all: true
  enable:
#    - goerr113 WIP
    - errcheck
    - goimports
    - revive
    - staticcheck
    - vet
    - forbidigo
run:
  skip-dirs:
    - ^ui
    - ^build
    - ^doc
    - ^.git
linters-settings:
  errcheck:
     severity: error
     confidence: 0.8
     rules:
       - name: unhandled-error
         arguments:
           - "*"

  revive:
     severity: error
     confidence: 0.8
     enable-all-rules: true
     rules:
       # Disabled rules
       - name: confusing-results
         disabled: true
       - name: add-constant
         disabled: true
       - name: argument-limit
         disabled: true
       - name: empty-lines
         disabled: true
       - name: exported
         disabled: true
       - name: function-length
         disabled: true
       - name: line-length-limit
         disabled: true
       - name: max-public-structs
         disabled: true
       - name: unused-receiver
         disabled: true
       - name: var-naming
         disabled: true
       - name: flag-parameter
         disabled: true

       # Rule tuning
       - name: cognitive-complexity
         arguments:
           - 50
       - name: cyclomatic
         arguments:
           - 30
       - name: function-result-limit
         arguments:
           - 4
       - name: unhandled-error
         arguments:
           - "fmt.*"
           - "bytes.Buffer.*"
           - "strings.Builder.*"
           - "os.File.Close"
           - "io.Closer.Close"
           - "zap.Logger.Sync"
           - "net.Conn.Close"
issues:
  exclude-rules:
    - path: pkg\/proc\/proc_file_creator\.go
      text: "unchecked-type-assertion: type cast result is unchecked in [^ ]+FileRecordHeapItem"
      linters:
        - revive
    - path: ^tests\/.+\.go
      text: cyclomatic|cognitive
      linters:
        - revive
    - path: .+\.go
      text: Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Sync|.*Flush|os\.Remove(All)?|.*print(f|ln)?|os\.(Un)?Setenv). is not checked
      linters:
        - errcheck
    - path: pkg\/xfer\/ssh\.go
      text: "SA1019: x509.IsEncryptedPEMBlock|SA1019: x509.DecryptPEMBlock"
      linters:
        - staticcheck
    - path: pkg\/proc\/proc_table_creator\.go
      text: function RunCreateTableRelForBatch has (cyclomatic|cognitive) complexity
      linters:
        - revive
    - path: pkg\/exe\/toolbelt\/capitoolbelt\.go
      text: function GetDotDiagram has cognitive complexity|function main has (cyclomatic|cognitive) complexity
      linters:
        - revive
    - path: pkg\/wf\/amqp_client\.go
      text: function amqpConnectAndSelect has cognitive complexity
      linters:
        - revive
    - path: pkg\/exe\/toolbelt\/.+\.go
      text: use of `fmt.Print(|f|ln)` forbidden by pattern
      linters:
        - forbidigo
