# https://golangci-lint.run/usage/configuration/#config-file
# ~/go/bin/golangci-lint run ./pkg/...
# gofmt -s -w ./pkg
linters:
  disable-all: true
  enable:
#    - goerr113
    - errcheck
#    - goimports
    # - paralleltest # missing the call to method parallel, but testify does not seem to work well with parallel test: https://github.com/stretchr/testify/issues/187
    - revive # revive supersedes golint, which is now archived
    - staticcheck
    - vet
#    - forbidigo
run:
#  skip-dirs:
#    - ^api
#    - ^proto
#    - ^.git
linters-settings:
#  govet:
#    fieldalignment: 0
#  forbidigo:
#    forbid:
#      - p: ^time\.After$
#        msg: "time.After may leak resources. Use time.NewTimer instead."
  errcheck:
     severity: error
     confidence: 0.8
     rules:
       - name: unhandled-error
         arguments:
           - "*"

  revive:
     severity: error
     confidence: 0.8
     enable-all-rules: true
     rules:
       # Disabled rules
       - name: confusing-results
         disabled: true
       - name: add-constant
         disabled: true
       - name: argument-limit
         disabled: true
#       - name: bare-return
#         disabled: true
#       - name: banned-characters
#         disabled: true
#       - name: bool-literal-in-expr
#         disabled: true
#       - name: confusing-naming
#         disabled: true
       - name: empty-lines
         disabled: true
#       - name: error-naming
#         disabled: true
#       - name: errorf
#         disabled: true
       - name: exported
         disabled: true
#       - name: file-header
#         disabled: true
       - name: function-length
         disabled: true
#       - name: imports-blacklist
#         disabled: true
#       - name: increment-decrement
#         disabled: true
       - name: line-length-limit
         disabled: true
       - name: max-public-structs
         disabled: true
#       - name: nested-structs
#         disabled: true
#       - name: package-comments
#         disabled: true
#       - name: string-format
#         disabled: true
#       - name: unexported-naming
#         disabled: true
#       - name: unexported-return
#         disabled: true
#       - name: unused-parameter
#         disabled: true
       - name: unused-receiver
         disabled: true
#       - name: use-any
#         disabled: true
       - name: var-naming
         disabled: true
#       - name: empty-block
#         disabled: true
       - name: flag-parameter
         disabled: true

       # Rule tuning
       - name: cognitive-complexity
         arguments:
           - 50
       - name: cyclomatic
         arguments:
           - 30
       - name: function-result-limit
         arguments:
           - 4
       - name: unhandled-error
         arguments:
           - "fmt.*"
           - "bytes.Buffer.*"
           - "strings.Builder.*"
           - "os.File.Close"
           - "io.Closer.Close"
           - "zap.Logger.Sync"
           - "net.Conn.Close"
issues:
   # Exclude cyclomatic and cognitive complexity rules for test and pkg/exe/deploy
  exclude-rules:
    - path: capideploy\.go|^tests\/.+\.go
      text: cyclomatic|cognitive
      linters:
        - revive
    - path: .+\.go
      text: Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Sync|.*Flush|os\.Remove(All)?|.*print(f|ln)?|os\.(Un)?Setenv). is not checked
      linters:
        - errcheck
#     - path: _test\.go|^common/persistence\/tests\/.+\.go # Ignore things like err = errors.New("test error") in tests
#       linters:
#         - goerr113
#     - path: ^tools\/.+\.go
#       linters:
#         - goerr113
#         - revive
