kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
    deployment: capitest
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        scrape_interval: 5s
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'node_exporter'
        scrape_interval: 5s
        static_configs:
          - targets: ['cassandra-0.cassandra.default.svc.cluster.local:7070','cassandra-1.cassandra.default.svc.cluster.local:7070']
