package msgsig

import (
	"crypto/ed25519"
	"crypto/rand"
	"encoding/base64"
	"encoding/json"
	"errors"
	"testing"

	"github.com/prometheus/client_golang/prometheus/testutil"
)

// newKeyPair returns a signer for kid and a verifier ring holding that kid's public key.
func newKeyPair(t *testing.T, kid string, mode Mode) (*Signer, *Verifier) {
	t.Helper()
	pub, priv, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		t.Fatalf("cannot generate key: %s", err)
	}

	// Use this as a quick key generator
	// fmt.Printf("pub: %s\npriv: %s\npriv with pub: %s\n", base64.StdEncoding.EncodeToString(pub), base64.StdEncoding.EncodeToString(priv.Seed()), base64.StdEncoding.EncodeToString(priv))

	signer, err := NewSigner(kid, base64.StdEncoding.EncodeToString(priv.Seed()))
	if err != nil {
		t.Fatalf("NewSigner: %s", err)
	}
	verifier, err := NewVerifier(mode, map[string]string{kid: base64.StdEncoding.EncodeToString(pub)})
	if err != nil {
		t.Fatalf("NewVerifier: %s", err)
	}
	return signer, verifier
}

// A test dummy pair generated by newKeyPair(). Also used in test config json files. Do not use in production.
const publicDummyKey string = "5tqw/Q6L9+sCUljNDTG3mhHY+vOOVWKI0EsPop8OSkg="
const privateDummyKey string = "MR91SD8QblIm25yuuF1hHfzZ1mn89NwgjTMGQ2g7Gr4=" // may contain just the private part (seed, 32 bytes), or both pri/pub keys (64 bytes)

func TestDummyKey(t *testing.T) {
	signer, err := NewSigner("dummy-key-do-not-use-in-production-see-msgsig-test-go-for-details", privateDummyKey)
	if err != nil {
		t.Fatalf("NewSigner: %s", err)
	}
	verifier, err := NewVerifier(ModeRequire, map[string]string{"dummy-key-do-not-use-in-production-see-msgsig-test-go-for-details": publicDummyKey})
	if err != nil {
		t.Fatalf("NewVerifier: %s", err)
	}
	payload := []byte(`{"id":"abc","script_url":"http://example/s.json"}`)

	sealed, err := signer.Seal(payload)
	if err != nil {
		t.Fatalf("Seal: %s", err)
	}
	opened, err := verifier.Open(sealed)
	if err != nil {
		t.Fatalf("Open: %s", err)
	}
	if string(opened) != string(payload) {
		t.Fatalf("payload mismatch: got %q want %q", opened, payload)
	}
}

func TestSealOpenRoundTrip(t *testing.T) {
	signer, verifier := newKeyPair(t, "key-1", ModeRequire)
	payload := []byte(`{"id":"abc","script_url":"http://example/s.json"}`)

	sealed, err := signer.Seal(payload)
	if err != nil {
		t.Fatalf("Seal: %s", err)
	}
	opened, err := verifier.Open(sealed)
	if err != nil {
		t.Fatalf("Open: %s", err)
	}
	if string(opened) != string(payload) {
		t.Fatalf("payload mismatch: got %q want %q", opened, payload)
	}
}

func TestSignerAcceptsFullPrivateKey(t *testing.T) {
	pub, priv, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		t.Fatalf("GenerateKey: %s", err)
	}
	// Full 64-byte private key (not the 32-byte seed).
	signer, err := NewSigner("k", base64.StdEncoding.EncodeToString(priv))
	if err != nil {
		t.Fatalf("NewSigner with full key: %s", err)
	}
	verifier, err := NewVerifier(ModeRequire, map[string]string{"k": base64.StdEncoding.EncodeToString(pub)})
	if err != nil {
		t.Fatalf("NewVerifier: %s", err)
	}
	sealed, err := signer.Seal([]byte("hi"))
	if err != nil {
		t.Fatalf("Seal: %s", err)
	}
	if _, err := verifier.Open(sealed); err != nil {
		t.Fatalf("Open: %s", err)
	}
}

func TestTamperedPayloadRejected(t *testing.T) {
	signer, verifier := newKeyPair(t, "key-1", ModeRequire)
	sealed, _ := signer.Seal([]byte(`{"id":"abc"}`))

	var env SignedEnvelope
	if err := json.Unmarshal(sealed, &env); err != nil {
		t.Fatalf("unmarshal: %s", err)
	}
	env.Payload = []byte(`{"id":"EVIL"}`)
	tampered, _ := json.Marshal(env)

	if _, err := verifier.Open(tampered); !errors.Is(err, ErrBadSignature) {
		t.Fatalf("expected ErrBadSignature, got %v", err)
	}
}

func TestTamperedKidRejected(t *testing.T) {
	signer, verifier := newKeyPair(t, "key-1", ModeRequire)
	sealed, _ := signer.Seal([]byte("data"))

	var env SignedEnvelope
	json.Unmarshal(sealed, &env)
	env.KeyId = "someone-else" // not in the ring -> ErrUnknownKey
	tampered, _ := json.Marshal(env)

	if _, err := verifier.Open(tampered); !errors.Is(err, ErrUnknownKey) {
		t.Fatalf("expected ErrUnknownKey, got %v", err)
	}
}

func TestTamperedAlgRejected(t *testing.T) {
	signer, verifier := newKeyPair(t, "key-1", ModeRequire)
	sealed, _ := signer.Seal([]byte("data"))

	var env SignedEnvelope
	json.Unmarshal(sealed, &env)
	env.Alg = "none" // downgrade attempt
	tampered, _ := json.Marshal(env)

	if _, err := verifier.Open(tampered); !errors.Is(err, ErrUnsupportedAlg) {
		t.Fatalf("expected ErrUnsupportedAlg, got %v", err)
	}
}

func TestTamperedVersionRejected(t *testing.T) {
	signer, verifier := newKeyPair(t, "key-1", ModeRequire)
	sealed, _ := signer.Seal([]byte("data"))

	var env SignedEnvelope
	json.Unmarshal(sealed, &env)
	env.Version = 99
	tampered, _ := json.Marshal(env)

	if _, err := verifier.Open(tampered); !errors.Is(err, ErrUnsupportedVersion) {
		t.Fatalf("expected ErrUnsupportedVersion, got %v", err)
	}
}

func TestTamperedSignatureRejected(t *testing.T) {
	signer, verifier := newKeyPair(t, "key-1", ModeRequire)
	sealed, _ := signer.Seal([]byte("data"))

	var env SignedEnvelope
	json.Unmarshal(sealed, &env)
	env.Signature[0] ^= 0xff // flip a bit
	tampered, _ := json.Marshal(env)

	if _, err := verifier.Open(tampered); !errors.Is(err, ErrBadSignature) {
		t.Fatalf("expected ErrBadSignature, got %v", err)
	}
}

func TestWrongSigningKeyRejected(t *testing.T) {
	// Sign with key A, verify against a ring that only knows key B (same kid).
	signerA, _ := newKeyPair(t, "shared-kid", ModeRequire)
	_, verifierB := newKeyPair(t, "shared-kid", ModeRequire)

	sealed, _ := signerA.Seal([]byte("data"))
	if _, err := verifierB.Open(sealed); !errors.Is(err, ErrBadSignature) {
		t.Fatalf("expected ErrBadSignature, got %v", err)
	}
}

func TestUnknownKidRejected(t *testing.T) {
	signer, err := NewSigner("kid-X", base64.StdEncoding.EncodeToString(mustSeed(t)))
	if err != nil {
		t.Fatalf("NewSigner: %s", err)
	}
	// Ring knows a different kid.
	_, verifier := newKeyPair(t, "kid-Y", ModeRequire)
	sealed, _ := signer.Seal([]byte("data"))
	if _, err := verifier.Open(sealed); !errors.Is(err, ErrUnknownKey) {
		t.Fatalf("expected ErrUnknownKey, got %v", err)
	}
}

func TestModeOffPassthrough(t *testing.T) {
	verifier, err := NewVerifier(ModeOff, nil)
	if err != nil {
		t.Fatalf("NewVerifier: %s", err)
	}
	raw := []byte(`{"id":"legacy"}`)
	opened, err := verifier.Open(raw)
	if err != nil {
		t.Fatalf("Open: %s", err)
	}
	if string(opened) != string(raw) {
		t.Fatalf("passthrough mismatch: got %q", opened)
	}
	// Nil verifier also passes through.
	var nilV *Verifier
	if opened, err := nilV.Open(raw); err != nil || string(opened) != string(raw) {
		t.Fatalf("nil verifier passthrough failed: %q %v", opened, err)
	}
}

func TestModePermissiveAcceptsSignedAndUnsigned(t *testing.T) {
	before := testutil.ToFloat64(VerifyUnsignedCounter)

	signer, verifier := newKeyPair(t, "key-1", ModePermissive)

	// Signed message opens to its payload.
	sealed, _ := signer.Seal([]byte(`{"id":"signed"}`))
	if opened, err := verifier.Open(sealed); err != nil || string(opened) != `{"id":"signed"}` {
		t.Fatalf("signed open failed: %q %v", opened, err)
	}

	// Legacy unsigned message (a bare wfmodel.Message JSON, no "v" field) is accepted and counted.
	legacy := []byte(`{"id":"legacy","script_url":"http://x"}`)
	opened, err := verifier.Open(legacy)
	if err != nil {
		t.Fatalf("permissive should accept unsigned: %v", err)
	}
	if string(opened) != string(legacy) {
		t.Fatalf("unsigned passthrough mismatch: %q", opened)
	}
	if got := testutil.ToFloat64(VerifyUnsignedCounter); got != before+1 {
		t.Fatalf("VerifyUnsignedCounter: got %v want %v", got, before+1)
	}
}

func TestModePermissiveRejectsBadSignature(t *testing.T) {
	// A present-but-invalid signature must be rejected even in permissive mode.
	signer, verifier := newKeyPair(t, "key-1", ModePermissive)
	sealed, _ := signer.Seal([]byte("data"))
	var env SignedEnvelope
	json.Unmarshal(sealed, &env)
	env.Signature[0] ^= 0xff
	tampered, _ := json.Marshal(env)

	if _, err := verifier.Open(tampered); !errors.Is(err, ErrBadSignature) {
		t.Fatalf("permissive must reject bad signature, got %v", err)
	}
}

func TestModeRequireRejectsUnsigned(t *testing.T) {
	_, verifier := newKeyPair(t, "key-1", ModeRequire)
	legacy := []byte(`{"id":"legacy"}`)
	if _, err := verifier.Open(legacy); !errors.Is(err, ErrUnsigned) {
		t.Fatalf("expected ErrUnsigned, got %v", err)
	}
}

func TestRequireEmptyRingIsError(t *testing.T) {
	if _, err := NewVerifier(ModeRequire, nil); err == nil {
		t.Fatalf("expected error for require mode with empty ring")
	}
}

func TestParseMode(t *testing.T) {
	cases := map[string]Mode{"": ModeOff, "off": ModeOff, "OFF": ModeOff, "permissive": ModePermissive, "require": ModeRequire}
	for in, want := range cases {
		got, err := ParseMode(in)
		if err != nil || got != want {
			t.Fatalf("ParseMode(%q) = %v, %v; want %v", in, got, err, want)
		}
	}
	if _, err := ParseMode("bogus"); err == nil {
		t.Fatalf("expected error for bogus mode")
	}
}

func TestNewSignerRejectsBadKey(t *testing.T) {
	if _, err := NewSigner("", "AAAA"); err == nil {
		t.Fatalf("expected error for empty kid")
	}
	if _, err := NewSigner("k", "not-base64!!!"); err == nil {
		t.Fatalf("expected error for bad base64")
	}
	if _, err := NewSigner("k", base64.StdEncoding.EncodeToString([]byte("too short"))); err == nil {
		t.Fatalf("expected error for wrong key length")
	}
}

func TestNewVerifierRejectsBadPublicKey(t *testing.T) {
	if _, err := NewVerifier(ModePermissive, map[string]string{"k": "not-base64!!!"}); err == nil {
		t.Fatalf("expected error for bad base64 public key")
	}
	if _, err := NewVerifier(ModePermissive, map[string]string{"k": base64.StdEncoding.EncodeToString([]byte("short"))}); err == nil {
		t.Fatalf("expected error for wrong public key length")
	}
}

func mustSeed(t *testing.T) []byte {
	t.Helper()
	_, priv, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		t.Fatalf("GenerateKey: %s", err)
	}
	return priv.Seed()
}
