name: Go coverage badge  # The name of the workflow that will appear on Github

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: stable

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -coverprofile=coverage.out -cover $(go list ./pkg/... | grep -e .*\.\/cql$ -e .*\.\/custom$ -e .*\.\/eval$ -e .*\.\/sc$ -e .*\.\/wf$)

    - name: Update coverage badge
      uses: ncruces/go-coverage-report@main
      with:
        coverage-file: coverage.out
        reuse-go: true
        amend: true