name: Go coverage badge

on: [push, pull_request]
jobs:
  test:
    name: Test with Coverage
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21'
    - name: Check out code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        go mod download
    - name: Run Unit tests
      run: |
        go test -coverprofile=/var/tmp/capillaries.p -cover $(go list ./pkg/... | grep -e .*\.\/cql$ -e .*\.\/custom$ -e .*\.\/eval$ -e .*\.\/sc$ -e .*\.\/wf$)
    - name: Install goveralls
      run: go install github.com/mattn/goveralls@latest
    - name: Send coverage
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: goveralls -coverprofile=/var/tmp/capillaries.p -service=github
    # or use shogo82148/actions-goveralls
    # - name: Send coverage
    #   uses: shogo82148/actions-goveralls@v1
    #   with:
    #     path-to-profile: /var/tmp/capillaries.p